name: LSIF
on:
  - push
jobs:
  lsif-go:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Generate LSIF data
        run: lsif-go
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
